version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
    shm_size: '1gb'
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      
    volumes:
      - /dev/shm:/dev/shm
  firefox:
    image: selenium/node-firefox:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  bdd:
     image: varsha/bddproject
     depends_on:
     - chrome
     - firefox
     environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - CUCUMBER_OPTIONS=classpath:features
     volumes:
      - ./output:/usr/share/udemy/reports/cucumber-reports
     
